#!/usr/sbin/nft -f

# TODO: Vider les règles précédentes (flush ruleset)

# TODO: Déclarer la table inet filter avec chaînes input, forward et output
# - input   : policy drop, loopback, conntrack, SSH LAN eth0, log drop
# - forward : policy drop, conntrack, LAN->WAN, LAN->DMZ, WAN->DMZ (80/443), log drop
# - output  : policy accept

# TODO: Déclarer la table ip nat avec chaînes prerouting et postrouting
# - prerouting  : DNAT ports 80/443 vers 192.168.50.10 sur eth1
# - postrouting : masquerade sur eth1
