# Interface WireGuard de la FILIALE (solution de référence)
# LAN filiale : 192.168.20.0/24 - NAT opérateur : 198.51.100.20

[Interface]
Address = 10.99.0.2/24
ListenPort = 51820
PrivateKey = 4GhJkLzXcVbNm0PoIuYtReWq1AsDfGhJ2KlZxCvBnM3=

# Transit firewall
PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp   = iptables -A FORWARD -o wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -o wg0 -j ACCEPT

[Peer]
# Passerelle du siège
PublicKey = mN0pQrStUvWx1Yz2Ab3Cd4Ef5Gh6Ij7Kl8Mn9Op0QrS=
Endpoint = 203.0.113.10:51820
AllowedIPs = 10.99.0.1/32, 192.168.10.0/24
PersistentKeepalive = 25