# Interface WireGuard du SIÈGE (solution de référence)
# LAN siège : 192.168.10.0/24 - IP publique : 203.0.113.10

[Interface]
Address = 10.99.0.1/24
ListenPort = 51820
PrivateKey = 6Kf0vX2mQ9Lp7TzR4nBwYc1aSd8EgHj3Kl5ZxCvBnM0=

# Transit réseau : autoriser le trafic du tunnel vers le LAN et retour
PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT
PostUp   = iptables -A FORWARD -o wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -o wg0 -j ACCEPT

[Peer]
# Passerelle filiale
PublicKey = u8Wj2xQf5RtY7UiOp1AsDfGhJkLzXcVbNm3QwE6RtYU0=
Endpoint = 198.51.100.20:51820
AllowedIPs = 10.99.0.2/32, 192.168.20.0/24