#!/usr/sbin/nft -f

# 1. Vidage complet des anciennes règles
flush ruleset

# 2. Table de filtrage IPv4 / IPv6
table inet filter {
    chain input {
        type filter hook input priority filter; policy drop;

        iif "lo" accept
        ct state invalid drop
        ct state { established, related } accept

        # Administration SSH depuis le LAN interne
        iif "eth0" tcp dport 22 ct state new accept

        # Journalisation des paquets rejetés
        log prefix "NFT-INPUT-DROP: " flags all counter drop
    }

    chain forward {
        type filter hook forward priority filter; policy drop;

        ct state invalid drop
        ct state { established, related } accept

        # 1. Flux LAN vers WAN (Navigation Internet)
        iif "eth0" oif "eth1" ct state new accept

        # 2. Flux LAN vers DMZ (Accès interne aux serveurs DMZ)
        iif "eth0" oif "eth2" ct state new accept

        # 3. Flux WAN vers DMZ (Reverse Proxy Web public)
        iif "eth1" oif "eth2" ip daddr 192.168.50.10 tcp dport { 80, 443 } ct state new accept

        # 4. Flux DMZ vers LAN : rejeté implicitement par la politique policy drop

        # Journalisation des rejets
        log prefix "NFT-FWD-DROP: " flags all counter drop
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}

# 3. Table de translation d'adresses (NAT)
table ip nat {
    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;

        # Redirection des flux Web externes vers le Reverse Proxy DMZ
        iif "eth1" tcp dport { 80, 443 } dnat to 192.168.50.10
    }

    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;

        # Masquage d'adresses lors de la sortie sur Internet
        oif "eth1" masquerade
    }
}
