# Serveur OpenVPN — SOLUTION INVALIDE : suite obsolète dans data-ciphers
# BF-CBC (Blowfish) est cassé : OpenVPN 2.5+ le refuse par défaut.

port 1194
proto udp
dev tun
server 10.8.0.0 255.255.255.0

ca   /etc/openvpn/pki/ca-racine.pem
cert /etc/openvpn/pki/vpn-server.crt
key  /etc/openvpn/pki/vpn-server.key
dh   none
tls-crypt /etc/openvpn/pki/ta.key

tls-version-min 1.2
data-ciphers AES-256-GCM:BF-CBC
auth SHA256

push "route 192.168.10.0 255.255.255.0"
push "dhcp-option DNS 192.168.10.5"