# Interface WireGuard de la FILIALE — SOLUTION INVALIDE : Endpoint manquant
# Sans Endpoint, le client ne sait pas où joindre le siège : le tunnel ne monte jamais.

[Interface]
Address = 10.99.0.2/24
ListenPort = 51820
PrivateKey = 4GhJkLzXcVbNm0=

PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT

[Peer]
PublicKey = mN0pQr=
AllowedIPs = 10.99.0.1/32, 192.168.10.0/24
PersistentKeepalive = 25