# Configuration dnsmasq - Services DNS et DHCP Agence
# ----------------------------------------------------

# 1. Configuration DNS
domain=agence.local
local=/agence.local/
listen-address=127.0.0.1,192.168.50.254

# Enregistrements d'hotes statiques
address=/srv-app.agence.local/192.168.50.10
address=/gw.agence.local/192.168.50.254

# 2. Configuration DHCP (Plage d'adresses et bail 12h)
dhcp-range=192.168.50.100,192.168.50.200,255.255.255.0,12h

# 3. Options DHCP
# Option 3 : Passerelle par defaut
dhcp-option=3,192.168.50.254
# Option 6 : Serveur DNS
dhcp-option=6,192.168.50.254
# Option 15 : Nom de domaine
dhcp-option=15,agence.local

# 4. Reservation DHCP statique (Imprimante)
dhcp-host=00:11:22:33:44:55,prn-agence,192.168.50.20
