# sysctl-security.conf - Paramètres du Noyau Linux Sécurisés

# TODO: Activer les TCP SYN Cookies

# TODO: Activer le filtrage Reverse Path (rp_filter)

# TODO: Désactiver les redirections ICMP

# TODO: Désactiver le routage IP

# TODO: Activer l'ASLR complet (randomize_va_space = 2)
