# Serveur TLS Nginx — SOLUTION INVALIDE : suites faibles subsistantes
# RC4 et 3DES sont cassées : la note SSL Labs chute et le RGS les interdit.

server {
    listen 443 ssl;
    server_name opensio.home.lan;

    ssl_certificate     /etc/nginx/pki/opensio.home.lan.crt;
    ssl_certificate_key /etc/nginx/pki/opensio.home.lan.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    # ERREUR : suites faibles RC4 et 3DES encore listées "en secours"
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:RC4-SHA:DES-CBC3-SHA;

    ssl_session_timeout 1d;
    ssl_session_cache shared:TLS:10m;
    ssl_session_tickets off;

    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 10.10.20.1 valid=300s;

    include /etc/nginx/snippets/security-headers.conf;
}

server {
    listen 80;
    server_name opensio.home.lan;
    return 301 https://$host$request_uri;
}