# /etc/wireguard/wg0.conf - Passerelle Siège GW-HQ

[Interface]
# TODO: Configurer Address, ListenPort et PrivateKey
PrivateKey = aHR0cHM6Ly9vcGVuc2lvLmxvY2FsL3ZwbmludGVybmV0aHE=

[Peer]
# TODO: Configurer PublicKey, Endpoint, AllowedIPs et PersistentKeepalive
PublicKey = c2VjdXJlX3B1YmxpY19rZXlfYnJhbmNoX3NpcnIyMDI2=
