# /etc/wireguard/wg0.conf - Passerelle Siège GW-HQ

[Interface]
Address = 10.100.0.1/30
ListenPort = 51820
PrivateKey = aHR0cHM6Ly9vcGVuc2lvLmxvY2FsL3ZwbmludGVybmV0aHE=

[Peer]
# Clé publique du routeur GW-BRANCH de l'agence
PublicKey = c2VjdXJlX3B1YmxpY19rZXlfYnJhbmNoX3NpcnIyMDI2=
Endpoint = 198.51.100.20:51820
AllowedIPs = 10.100.0.2/32, 192.168.20.0/24
PersistentKeepalive = 25
