! Configuration FRRouting / OSPFv2 pour R1-CORE
frr version 8.5
frr defaults traditional
hostname R1-CORE
log syslog informational
no ip forwarding
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.255.255.1/32
!
interface eth0
 description LAN Utilisateurs
 ip address 192.168.100.254/24
!
interface eth1
 description Interconnexion vers R2 (10 Gbps)
 ip address 10.0.0.1/30
!
interface eth2
 description Interconnexion vers R3 (1 Gbps)
 ip address 10.0.0.5/30
!
router ospf
 ! TODO: Configurer router-id, reference-bandwidth, passive-interface, network et default-information originate
!
line vty
!
