! Configuration FRRouting / OSPFv2 pour R1-CORE
frr version 8.5
frr defaults traditional
hostname R1-CORE
log syslog informational
service integrated-vtysh-config
!
interface lo
 ip address 10.255.255.1/32
!
interface eth0
 description LAN Utilisateurs
 ip address 192.168.100.254/24
!
interface eth1
 description Interconnexion vers R2 (10 Gbps)
 ip address 10.0.0.1/30
 ip ospf cost 10
!
interface eth2
 description Interconnexion vers R3 (1 Gbps)
 ip address 10.0.0.5/30
 ip ospf cost 100
!
router ospf
 ospf router-id 10.255.255.1
 auto-cost reference-bandwidth 100000
 passive-interface eth0
 network 10.255.255.1/32 area 0
 network 10.0.0.0/30 area 0
 network 10.0.0.4/30 area 0
 network 192.168.100.0/24 area 0
 default-information originate
!
line vty
!
